In [173]:
                                         # Setup #
import numpy as np
np.random.seed(42)

In [175]:
                                    # Simulate Sensor Data #
image_size = (100, 5)
sensor_data = np.zeros(image_size, dtype=np.float64)

#Filling array
sensor_data[:, 0] = np.random.normal(25, 5, 100)
sensor_data[:, 1] = np.linspace(10, 30, 100) + np.random.normal(0, 2, 100)
sensor_data[:, 2:] = np.random.uniform(low=0.0, high=100.0, size=(100,3))

print(sensor_data[0:4, :])

[[27.48357077  7.16925852 87.73730719 74.07686178 69.7015741 ]
 [24.30867849  9.36072956 70.2484084  35.94911512 29.35918443]
 [28.23844269  9.71861137 80.93611555 81.01133947 86.70723186]
 [32.61514928  9.00150607 91.32405526 51.13423989 50.15162947]]


In [177]:
                                    # Handling Outliers/Noise #
# Simulate Outliers
sensor_data[0, 0] = 500
sensor_data[74, 1] = 500
sensor_data[40, 2] = 500
sensor_data[27, 3] = 500
sensor_data[53, 4] = 500

#Identify and Replace Outliers
rows_over_100, cols_over_100 = np.where(sensor_data > 100)
sensor_data[rows_over_100, cols_over_100] = np.NaN
COPY_data = sensor_data.copy
median = np.nanmedian(sensor_data, overwrite_input=True, keepdims=True,)



[[28.32021262]]
